# Generated by Django 3.2.8 on 2021-11-06 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailHarga',
            fields=[
                ('id_detail_harga', models.AutoField(db_column='ID_DETAIL_HARGA', primary_key=True, serialize=False)),
                ('tanggal', models.DateField(db_column='TANGGAL')),
                ('harga', models.DecimalField(db_column='HARGA', decimal_places=2, max_digits=11)),
                ('status_aktif', models.IntegerField(db_column='STATUS_AKTIF')),
            ],
            options={
                'db_table': 'detail_harga',
            },
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id_lokasi', models.AutoField(db_column='ID_LOKASI', primary_key=True, serialize=False)),
                ('nama_lokasi', models.CharField(db_column='NAMA_LOKASI', max_length=255)),
                ('status_lokasi', models.IntegerField(db_column='STATUS_LOKASI')),
            ],
            options={
                'db_table': 'lokasi',
            },
        ),
        migrations.CreateModel(
            name='MasterMutu',
            fields=[
                ('id_master_mutu', models.AutoField(db_column='ID_MASTER_MUTU', primary_key=True, serialize=False)),
                ('nama_master_mutu', models.CharField(db_column='NAMA_MASTER_MUTU', max_length=255)),
                ('status_master_mutu', models.IntegerField(blank=True, db_column='STATUS_MASTER_MUTU', null=True)),
            ],
            options={
                'db_table': 'master_mutu',
            },
        ),
        migrations.CreateModel(
            name='SatuanMaterial',
            fields=[
                ('id_satuan', models.AutoField(db_column='ID_SATUAN', primary_key=True, serialize=False)),
                ('nama_satuan', models.CharField(db_column='NAMA_SATUAN', max_length=255)),
            ],
            options={
                'db_table': 'satuan_material',
            },
        ),
        migrations.CreateModel(
            name='UserBmi',
            fields=[
                ('id_user', models.CharField(db_column='ID_USER', max_length=10, primary_key=True, serialize=False)),
                ('nama_user', models.CharField(db_column='NAMA_USER', max_length=255)),
            ],
            options={
                'db_table': 'user_bmi',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(db_column='ID_SUPPLIER', primary_key=True, serialize=False)),
                ('nama_supplier', models.CharField(db_column='NAMA_SUPPLIER', max_length=255)),
                ('kode_sap', models.CharField(db_column='KODE_SAP', max_length=10)),
                ('no_rek', models.CharField(db_column='NO_REK', max_length=255)),
                ('id_lokasi', models.ForeignKey(blank=True, db_column='ID_LOKASI', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_crabs.lokasi')),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('no_receiving', models.CharField(db_column='NO_RECEIVING', max_length=10, primary_key=True, serialize=False)),
                ('tanggal_terima', models.DateField(db_column='TANGGAL_TERIMA')),
                ('jumlah_berat', models.DecimalField(db_column='JUMLAH_BERAT', decimal_places=0, max_digits=10)),
                ('id_detail_harga', models.ForeignKey(blank=True, db_column='ID_DETAIL_HARGA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_crabs.detailharga')),
                ('id_user', models.ForeignKey(blank=True, db_column='ID_USER', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_crabs.userbmi')),
            ],
            options={
                'db_table': 'receiving',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(db_column='ID_MATERIAL', primary_key=True, serialize=False)),
                ('nama_material', models.CharField(db_column='NAMA_MATERIAL', max_length=255)),
                ('status_material', models.IntegerField(blank=True, db_column='STATUS_MATERIAL', null=True)),
                ('id_satuan', models.ForeignKey(blank=True, db_column='ID_SATUAN', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_crabs.satuanmaterial')),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.AddField(
            model_name='detailharga',
            name='id_master_mutu',
            field=models.ForeignKey(blank=True, db_column='ID_MASTER_MUTU', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_crabs.mastermutu'),
        ),
        migrations.AddField(
            model_name='detailharga',
            name='id_material',
            field=models.ForeignKey(blank=True, db_column='ID_MATERIAL', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_crabs.material'),
        ),
        migrations.AddField(
            model_name='detailharga',
            name='id_supplier',
            field=models.ForeignKey(blank=True, db_column='ID_SUPPLIER', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_crabs.supplier'),
        ),
    ]
